### ISSUE TITLE
Consider changing printing individual imports to ``import X items``

### ISSUE THREAD

**Issue by kendonB** [wlandau-lilly/drake#133]
From:
```
import geosphere::distHaversine
import stringi::stri_rand_strings
import .I
import which.max
import if_else
import purrr::pmap
import distinct
import raster::crop
import nas
import res
missing nas
```
To:
```
importing X items: geosphere::distHaversine...
missing 1 import items: nas
```

Could even do without the ``missing`` message probably.

**Comment by kendonB** [comment]
Is it not feasible / easy to print the imports in chunks between mixing with targets?

**Comment by wlandau-lilly** [comment]
Because of parallel processing, no. If we have both imports and targets in a parallelizable stage, the print order is a race condition. I am resistant to manually changing this order because then it will no longer reflect when targets/imports are really being process. 

I am disappointed but convinced that this particular idea will not work out. But it was a really good idea.
