### ISSUE TITLE
skip checking connections when trigger = "missing"

### ISSUE THREAD

**Issue by kendonB** [wlandau-lilly/drake#142]
just getting around to testing these new features now. Superb that you were able to get the trigger feature implemented.

I find that drake unnecessarily checks connections for targets for which I have  set ``trigger = "missing"``.

**Comment by wlandau-lilly** [comment]
@kendonB thank you for testing the triggers!

Even with the `missing` trigger, I still think it is important to check connections in order to make sure the missing targets get built in the correct order. Even for users who want `drake` to disregard reproducibility and just act as a job scheduler, final summaries and reports cannot be computed before the datasets have finished generating, for example.

**Comment by kendonB** [comment]
You're right.

**Comment by wlandau-lilly** [comment]
You do have a fair point, though. Connecting takes a long time in projects as massive as yours, and there may be ways to cut out some of the work. I just have trouble thinking of elegant ways to get around building the whole graph.
