### ISSUE TITLE
target is consistently failing to storr properly

### ISSUE THREAD

**Issue by kendonB** [wlandau-lilly/drake#159]
I have tried to build a target a few times and it consistently fails to storr.

I've gone through several iterations of:

```
make(...)
# Error in readRDS(self$name_hash(hash)) : error reading from connection occurs reading target1
rescue_cache("target1")
make(...)
# Error in readRDS(self$name_hash(hash)) : error reading from connection occurs reading target1
```

I've dived in and I can see the target successfully builds but I haven't been able to find the piece of code that actually calls the storr code. What do I need to ``debug``?

Is it also possible that something else that ``drake`` or ``storr`` needs to read ``target1`` is corrupted?

**Comment by kendonB** [comment]
I did also do an untargeted ``rescue_cache`` and it didn't seem to solve the problem.

**Comment by wlandau-lilly** [comment]
@kendonB You might have a look at the functions in [build.R](https://github.com/wlandau-lilly/drake/blob/master/R/build.R), particularly [storr_target()](https://github.com/wlandau-lilly/drake/blob/master/R/build.R#L118). I also have some questions:

- What kind of target is this? A true target with a command? Is the output a file, a function, or a generic R object?
- What part of the code throws `"Error in readRDS(self$name_hash(hash))"`?
- What `storr` namespace is `drake` trying to read from when it throws the error?
- Does the error happen during `make()`, `readd()`, or something else?

**Comment by wlandau-lilly** [comment]
Does the error happen in the [call to `loadd()`](https://github.com/wlandau-lilly/drake/blob/master/R/envir.R#L49) in [prune_envir()](https://github.com/wlandau-lilly/drake/blob/master/R/envir.R#L11)?

**Comment by wlandau-lilly** [comment]
Another thing: [here](https://github.com/wlandau-lilly/drake/issues/154#issuecomment-344798972), I describe some recent changes to the cache format that were supposed to be back compatible with previous commits. I was trying to reduce the number of files in the cache, and I removed the `"readd"` namespace in favor of the default namepace. I was not suspecting this to be a problem because I was using the approach in richfitz/storr#56 to duplicate namespaces. It is a shot in the dark, but you might try `get_cache()$clear(namespace = "readd")` if all else fails.

**Comment by kendonB** [comment]
This is a true target with a command. Output is an R object.

I think I fixed the problem for now, so I can't verify exactly where the error occurs in ``readd`` - I think its in a ``$get`` function.

It was failing reading from the "objects" namespace.

The error occured during both ``make`` and ``readd``.

I narrowed the problem down to here in ``storr:::set_value``:

```r
set_value = function(value, use_cache = TRUE) {
      value_ser <- self$serialize_object(value)
      hash <- self$hash_raw(value_ser)

      if (!(use_cache && exists0(hash, self$envir))) {
        ## NOTE: This exists/set roundtrip here always seems useful to
        ## avoid sending (potentially large) data over a connection, but
        ## it's possible that some drivers could do this more
        ## efficiently themselves during negotiation.
        if (!self$driver$exists_object(hash)) {
          value_send <- if (self$traits$accept == "object") value else value_ser
          self$driver$set_object(hash, value_send)
        }
        if (use_cache) {
          assign(hash, value, self$envir)
        }
      }
      invisible(hash)
    }
```

The problem seemed to be that the code never got to ``self$driver$set_object(hash, value_send)`` to update the target, even though it doesn't exist, but it must exist somewhere?? ``exists0(hash, self$envir)`` was ``TRUE`` when it seems like it should have been ``FALSE``.

Let's hope this was a temporary problem caused by your recent changes to the cache format.

**Comment by wlandau-lilly** [comment]
That does sound like the sort of thing that I may have caused by removing the `"readd"` namespace. I am glad you narrowed it down to `readd()`, which is much simpler than `make()`, and then to `storr` itself. If this problem happens again without any change to `drake`'s cache format, the issue may belong in the `storr` issue tracker, depending on how it reemerges.
