### ISSUE TITLE
vis_drake_graph or drake_config uses absolute paths in the background

### ISSUE THREAD

**Issue by kendonB** [wlandau-lilly/drake#197]
Sharing a drake cache via dropbox, ran ``vis_drake_graph(read_drake_config())`` and got:

```
In (if (compress) gzfile else file)(filename, "wb") :
  cannot open compressed file 'MY_COLLEAGUES_PATH/.drake/data/9882e97b88564731.rds', probable reason 'No such file or directory'
```
should change these to relative paths, I believe.

**Comment by wlandau-lilly** [comment]
Good catch, Kendon. The problem is that `read_drake_config()` reads in an `storr` object that points to the previous cache. Here is what your colleague sees.

```r
make(good_plan) # Automatically saves the config list.
config <- read_drake_config() # Get the last saved config
cache <- config$cache # storr cache object that was saved in make()
cache$driver$path

## /your/colleagues/path/.drake
```

When you download your colleague's project, the config object you read has no idea that the file system was relocated.

```r
getwd()

## /your/path

read_drake_config()cache$driver$path

## /your/colleagues/path/.drake
```

Fixing this is just a matter of replacing the stored cache object with the moved cache from which you actually read your colleague's `config`. I am about to upload a patch.

**Comment by wlandau-lilly** [comment]
I still think cache paths should be absolute. Otherwise, the following would fail. 
See richfitz/storr#50.

```r
make(your_plan) # Create a cache.
cache <- drake::get_cache() # Explore some results.
cache$get("my_object")       # This part would work regardless.
setwd("some/other/path")    # The relative path changes, but not the absolute path.
cache$get("my_object")       # The relative path would incorrectly factor through 'some/other/path'.
```
