### ISSUE TITLE
Play nicer with devtools::load_all()

### ISSUE THREAD

**Issue by wlandau-lilly** [wlandau-lilly/drake#30]
Packages loaded by the user before `make()` need to be loaded again for each process in some of the more advanced forms of parallel computing. That's the whole point of the `packages` and `prework` arguments.

Maybe drake should try `require()` first and then `devtools::load_all(pkg = path_to_package)` if that fails. But then I need to know `path_to_package`, so it may not be such a trivial fix. But since packages are loaded before any prework is done or any targets are made, this is not likely to exacerbate #13.

**Comment by wlandau-lilly** [comment]
There are apparently more problems with `devtools::load_all()` and drake:

```r
> library(drake)
> prework = "devtools::load_all('JeffLeekMeme')" # git clone git@github.com:wlandau/JeffLeekMeme
> myplan = plan(x = JeffLeek())
> myplan
  target    command
1      x JeffLeek()
> make(myplan, prework = prework, parallelism = "parLapply", jobs = 2)
starting worker pid=24776 on localhost:11421 at 11:55:58.164
starting worker pid=24806 on localhost:11421 at 11:55:58.435
Loading JeffLeekMeme
Loading JeffLeekMeme
import JeffLeek
Warning: namespace 'JeffLeekMeme' is not available and has been replaced
by .GlobalEnv when processing object ''
build x
Any statistic is a sufficient statistic when itâs Jeff Leek using it. - David Robinson
```

And if `devtools::load_all("JeffLeekMeme")` is called before `make()` in the code, there is an actual error if `parallelism = "parLapply"` and `jobs = 2`.

**Comment by wlandau-lilly** [comment]
After reflecting on duncantl/CodeDepends#16, `devtools::load_all()` no longer seems like a big deal. It is reasonable to have to include it in the `prework` rather than `packages` and expect possible warnings with `parLapply()` parallelism. Will reopen on request.

**Comment by dapperjapper** [comment]
I don't totally understand how environments work, but I've been struggling to use drake within a package format with devtools, and it turns out that this works for me:

```r
env = devtools::load_all()$env
drake::make(my_plan, envir = env)
```

I'm posting this for posterity. Please LMK if this has unseen implications or something!

**Comment by wlandau-lilly** [comment]
Interesting, I did not know you could get an environment from `load_all()`. What exactly went wrong for Makefile parallelism? My guess is that R treats package environments differently somehow. You may have to deep copy the environment into a different one first. Slow and inefficient, but maybe worth a shot. If it works, it should definitely go in a vignette or example.

```r
env = devtools::load_all()$env
e <- list2env(as.list(env), parent = globalenv())
drake::make(my_plan, envir = env, parallelism = "Makefile", jobs = 2)
```

Also, feel free to weigh in on #6. The eventual solution could affect how this sort of situation is handled. I too like to put as much into packages as I can, including data analysis workflows.

**Comment by dapperjapper** [comment]
Ok, after a bunch of trial and error, here's a version that runs with Makefile parallelism without errors or warnings:

```r
env <- devtools::load_all()$env
env <- list2env(as.list(env), parent = globalenv())

# Set the environment of every function in
# our package to our copied environment env.
for (n in ls(env))
  assign(n,
         envir = env,
         value =
           `environment<-`( get(n, envir = env), env )
         )

my_plan <- get_plan()

drake::make(my_plan,
            envir = env,
            jobs = 4, parallelism = "Makefile",
            packages = setdiff(.packages(), "YOURDEVTOOLSPACKAGENAME"))
```

Here's what the issue was: first of all, package namespace environments are treated differently than normal environments, so I had to use your line to copy the environment with `list2env`. I don't know if there's a more elegant way to do this, or if something within drake needs to be changed. Here is the line in drake that caused the problem: (Makefile.R)

```r
if (identical(globalenv(), config$envir)){
```

Then, the issue became that functions that referenced other functions in the package couldn't see each-other. It turns out that the environment for functions is set when they are first defined, so `eval(envir = )` didn't effect the execution environment within the function! To fix this, I had to manually move over the environment binding for each function within the package using `environment<-`. This is a hacky fix, and might break if you have non-functions defined in the environment?

Anyway: this seems like a common-ish use case for drake, and should definitely be written into a vignette. If it makes sense to you, we could also think about ways to integrate this fix into drake.

**Comment by wlandau-lilly** [comment]
I am impressed. I spent two months trying to figure out how to handle environments in the early days of drake, and I could not find a way to change the environment bindings the way you did.

However, I am hesitant to change the core internals of drake to accommodate this use case. I like leaving the evaluation environment alone (except for adding and removing built targets) so the users know exactly what they are getting. Whenever I tried reconfiguring the environment, whether the user's environment or a new isolated one, I always ran into lexical scoping problems eventually. Plus, if `f <-Vectorize(...)`, then the original function is stored in `environment(f)$FUN`.

If you want to write a vignette and/or an [example](https://github.com/wlandau-lilly/drake/tree/master/inst/examples), I would gladly accept it.
